datasets:
  enem:
    name: ENEM
    destination: data/landing/enem
    file_name: enem.zip
    url: ""

  ibge:
    name: IBGE
    destination: data/landing/ibge
    file_name: municipios.json
    url: "https://servicodados.ibge.gov.br/api/v1/localidades/municipios"

  censo:
    name: Censo Escolar
    destination: data/landing/censo_escolar
    file_name: censo.zip
    url: ""